from django.urls import path
from . import views

urlpatterns = [
    path("redirect/", views.post_login_redirect, name="post_login"),
    path("doctor/", views.doctor_dashboard, name="doctor_dashboard"),
    path("nurse/", views.nurse_dashboard, name="nurse_dashboard"),
    path("reception/", views.reception_dashboard, name="reception_dashboard"),
    path("lab/", views.lab_dashboard, name="lab_dashboard"),
    path("pharmacy/", views.pharmacy_dashboard, name="pharmacy_dashboard"),
    path("cashier/", views.cashier_dashboard, name="cashier_dashboard"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("stock/", views.stock_dashboard, name="stock_dashboard"),
    path("patient/", views.patient_dashboard, name="patient_dashboard"),
    path("", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("patients/", views.patient_list, name="patient_list"),
    path("patients/new/", views.patient_create, name="patient_create"),
    path("appointments/", views.appointment_list, name="appointment_list"),
    path("appointments/new/", views.appointment_create, name="appointment_create"),
    path("appointments/<int:pk>/checkin/", views.appointment_checkin, name="appointment_checkin"),
    path("appointments/<int:pk>/meeting-link/", views.set_meeting_link, name="set_meeting_link"),
    path("visits/<int:pk>/", views.visit_detail, name="visit_detail"),
    path("visits/<int:pk>/start/", views.visit_start, name="visit_start"),
    path("visits/<int:pk>/vitals/", views.visit_record_vitals, name="visit_record_vitals"),
    path("visits/<int:pk>/diagnosis/", views.visit_record_diagnosis, name="visit_record_diagnosis"),
    path(
        "visits/<int:pk>/prescription/add/",
        views.visit_add_prescription_item,
        name="visit_add_prescription_item",
    ),
    path("visits/<int:pk>/lab-tests/add/", views.visit_add_lab_test, name="visit_add_lab_test"),
    path("visits/<int:pk>/complete/", views.visit_complete, name="visit_complete"),
    path("pharmacy/visits/<int:pk>/", views.prescription_detail, name="prescription_detail"),
    path(
        "pharmacy/visits/<int:pk>/items/<int:item_pk>/dispense/",
        views.dispense_item,
        name="dispense_prescription_item",
    ),
    path("lab/visits/<int:pk>/", views.lab_order_detail, name="lab_order_detail"),
    path(
        "lab/visits/<int:pk>/items/<int:item_pk>/result/",
        views.record_lab_result,
        name="record_lab_result",
    ),
    path("cashier/visits/<int:pk>/", views.visit_invoice_detail, name="visit_invoice_detail"),
    path("cashier/visits/<int:pk>/items/add/", views.add_invoice_item, name="add_invoice_item"),
    path("cashier/visits/<int:pk>/payments/add/", views.record_payment, name="record_payment"),
    path("nurse/visits/<int:pk>/", views.nurse_triage, name="nurse_triage"),
    path("nurse/visits/<int:pk>/vitals/", views.nurse_record_vitals, name="nurse_record_vitals"),
    path("stock/drugs/<int:pk>/", views.drug_stock_detail, name="drug_stock_detail"),
    path("stock/drugs/<int:pk>/receive/", views.receive_stock, name="receive_stock"),
    path("stock/drugs/<int:pk>/adjust/", views.adjust_stock, name="adjust_stock"),
    path("doctor/refill-requests/<int:pk>/approve/", views.refill_request_approve, name="refill_request_approve"),
    path("doctor/refill-requests/<int:pk>/deny/", views.refill_request_deny, name="refill_request_deny"),
    path("patient/prescription-refill/", views.prescription_refill, name="prescription_refill"),
    path(
        "patient/prescription-refill/<int:item_pk>/request/",
        views.request_refill,
        name="request_refill",
    ),
    path("patient/telemedicine/", views.telemedicine_start, name="telemedicine_start"),
    path("patient/telemedicine/history/", views.telemedicine_history, name="telemedicine_history"),
    path("patient/records/", views.records_download, name="records_download"),
    path("lab_result_list/", views.lab_result_list, name="lab_result_list"),
    path("invoice_list/", views.invoice_list, name="invoice_list"),
]
