# Generated by Django 6.0.6 on 2026-07-08 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items_dispensed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
