# Generated by Django 6.0.6 on 2026-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('IN_PERSON', 'In Person'), ('TELEMEDICINE', 'Telemedicine')], default='IN_PERSON', max_length=20),
        ),
    ]
